linters:
  HexValidation:
    enabled: false
  LeadingZero:
    enabled: false
  ColorVariable:
    enabled: false
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorFormat:
    enabled: false
